import type { Metadata } from 'next'

// Next.js replaces (not deep-merges) a parent `openGraph` object when a child
// segment defines its own — so any page setting a per-page og:url must re-spread
// these shared fields. The OG image itself is generated by the file-based
// `opengraph-image.tsx` convention, so it is intentionally not listed here.
export const ogDefaults: NonNullable<Metadata['openGraph']> = {
  type: 'website',
  siteName: 'ATTIC',
}
